### ISSUE TITLE
.jar GUI?

### ISSUE THREAD

**Issue by zazasmeller** [trekawek/coffee-gb#27]
is there or can you make a gui for the .jar in the releases?

i can’t use terminal

**Comment by trekawek** [comment]
Sorry, there's no GUI for now. To be honest, I haven't spent too much time on the user experience part of the program, since there are many emulators with excellent GUIs that can be used to play GB/GBC games. I considered this one more like a development exercise, with some emphasis on the accuracy.

That being said, I've been looking for some challange lately and maybe adding a GUI would be good one.
